### PR TITLE
Add problem quickfix opening

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by jpeterka** [comment]
Test should be more complex. Specific quickfix content should be checked and also there should be test that quickfix is applied correctly.

**Comment by rawagner** [comment]
Test updated

**Comment by jpeterka** [comment]
please rebase

**Comment by rawagner** [comment]
test this

**Pull request merged**
