### PR TITLE
rev_Keyboard readAndDispatch sync cycle can lead to frozen test

### PR DESCRIPTION
**Pull request by jpeterka**
http://machydra.brq.redhat.com:8080/view/RedDeer/job/RedDeer_verification_matrix/2282/jdk=sunjdk1.7,label=stable-linux/console

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
test this

**Comment by jpeterka** [comment]
test this

**Comment by jpeterka** [comment]
test this

**Comment by jpeterka** [comment]
verification job results: http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1449/artifact/reddeermatrixtestresults.html

**Pull request merged**
