### PR TITLE
Method WidgetResolver.getParent(Widget) is fixed

### PR DESCRIPTION
**Pull request by scabanovich**
This method should match method getChildren(Widget).
Together they should allow to navigate the tree of widgets
in a consistent way.
Test is added.

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by rawagner** [comment]
ok to test

**Comment by rawagner** [comment]
for 1.0.x

**Comment by apodhrad** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
pushed to master

**Pull request closed without merging**
