### PR TITLE
Initial code generator

### PR DESCRIPTION
**Pull request by apodhrad**
Add a feature to generate code from wizards, shells, views, etc.

How will it work?
Just focus on a wizard or view a press a key shortcut with will generate a RedDeer code into a view or some standalone shell.

### CODE REVIEW

**Comment by apodhrad** [comment]
In the future the recorder will depends on these generators

**Comment by vpakan** [comment]
* CodeGeneratorViewTest.openCodeGeneratorViewTest default
* org.jboss.reddeer.generator.test about.html should contain year 2015 instead of 2010
* org.jboss.reddeer.generator should also contain about.html probably
* can you use different shortcut than CTRL+SHIFT for starting generator this shortcut is used via Eclipse Spy

**Comment by apodhrad** [comment]
* Now the shortcut is Alt + g
* Feature is not added to site/category.xml since it is part of recorder feature (in the future recorder will dependent on generator bundle)
* The rest should be fixed

**Comment by vpakan** [comment]
plugins/org.jboss.reddeer.generator/build.properties - should contain about.html

**Comment by apodhrad** [comment]
done

**Pull request closed without merging**
