### PR TITLE
RedDeer 1.2.0 release

### PR DESCRIPTION
**Pull request by mmalina**
Command used for upversioning:
mvn org.eclipse.tycho:tycho-versions-plugin:0.22.0:set-version -DnewVersion=1.2.0.Final
(For some reason the latest version - 0.26.0 - is broken and does not work.)

In addition, these files were modified manually:
archetype/src/main/resources/archetype-resources/pom.xml
archetype/pom.xml

And this file should also be checked, although most probably the RedDeer
version will be correct already:
archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
This time I had to change mars to neon there.

### CODE REVIEW

**Comment by apodhrad** [comment]
@mmalina could you provide the error so that we can investigate what's wrong with the tycho 0.26.0, please?

**Comment by mmalina** [comment]
@apodhrad you can try it for yourself. Just run:
mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=1.2.0.Final

Both Rasto and me saw the errors.
I wanted to run it now to post the output here, but for some reason the maven build is terribly slow for me right now. I will post here if I can get maven to work later.

**Comment by rawagner** [comment]
pushed to master. Thanks @mmalina !

**Comment by mmalina** [comment]
@apodhrad 
`[INFO] Building Red Deer Parent POM File 1.2.0.Final
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- tycho-versions-plugin:0.26.0:set-version (default-cli) @ parent ---
[WARNING] Error injecting: org.eclipse.tycho.versions.manipulation.P2iuXmlManipulator
java.lang.NoClassDefFoundError: org/eclipse/tycho/model/IU
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:613)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:569)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:555)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1006)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1038)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.eclipse.sisu.wire.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:111)
	at org.eclipse.tycho.versions.engine.VersionsEngine.apply(VersionsEngine.java:112)
	at org.eclipse.tycho.versions.SetMojo.execute(SetMojo.java:125)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.eclipse.tycho.model.IU
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 62 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Red Deer Parent POM File ........................... FAILURE [  0.145 s]
[INFO] Red Deer Plugins ................................... SUCCESS [  0.001 s]
[INFO] Red Deer Common .................................... SUCCESS [  0.010 s]
[INFO] Red Deer Core ...................................... SUCCESS [  0.050 s]
[INFO] Red Deer JUnit Support ............................. SUCCESS [  0.017 s]
[INFO] Red Deer SWT Component ............................. SUCCESS [  0.029 s]
[INFO] Red Deer JFace Component ........................... SUCCESS [  0.008 s]
[INFO] Red Deer Workbench Component ....................... SUCCESS [  0.011 s]
[INFO] Red Deer UI Forms Components ....................... SUCCESS [  0.009 s]
[INFO] Red Deer Direct .................................... SUCCESS [  0.005 s]
[INFO] Red Deer Eclipse Component ......................... SUCCESS [  0.057 s]
[INFO] Red Deer GEF Component ............................. SUCCESS [  0.014 s]
[INFO] Red Deer GEF Spy Component ......................... SUCCESS [  0.007 s]
[INFO] Red Deer Graphiti Component ........................ SUCCESS [  0.009 s]
[INFO] Red Deer JUnit Extensions .......................... SUCCESS [  0.009 s]
[INFO] Red Deer Selenium Component ........................ SUCCESS [  0.004 s]
[INFO] Red Deer Examples .................................. SUCCESS [  0.008 s]
[INFO] Red Deer Requirements Support ...................... SUCCESS [  0.012 s]
[INFO] Red Deer UI Component .............................. SUCCESS [  0.011 s]
[INFO] Red Deer Spy ....................................... SUCCESS [  0.006 s]
[INFO] Red Deer Recorder .................................. SUCCESS [  0.010 s]
[INFO] Red Deer Branding Component ........................ SUCCESS [  0.002 s]
[INFO] Red Deer Code Generator Component .................. SUCCESS [  0.006 s]
[INFO] Red Deer Go ........................................ SUCCESS [  0.004 s]
[INFO] Red Deer Log Parser ................................ SUCCESS [  0.016 s]
[INFO] Red Deer Tests ..................................... SUCCESS [  0.001 s]
[INFO] Red Deer Common Component Tests .................... SUCCESS [  0.005 s]
[INFO] Red Deer Core Component Tests ...................... SUCCESS [  0.005 s]
[INFO] Red Deer SWT Component Tests ....................... SUCCESS [  0.024 s]
[INFO] Red Deer Workbench Component Tests ................. SUCCESS [  0.008 s]
[INFO] Red Deer UI Forms Components Test .................. SUCCESS [  0.007 s]
[INFO] Red Deer JFace Component Tests ..................... SUCCESS [  0.009 s]
[INFO] Red Deer Eclipse Component Tests ................... SUCCESS [  0.029 s]
[INFO] Red Deer GEF Component Tests ....................... SUCCESS [  0.006 s]
[INFO] Red Deer Graphiti Component Tests .................. SUCCESS [  0.005 s]
[INFO] Red Deer Direct Component Tests .................... SUCCESS [  0.005 s]
[INFO] Red Deer JUnit Component Tests ..................... SUCCESS [  0.025 s]
[INFO] Red Deer Requirements Tests ........................ SUCCESS [  0.109 s]
[INFO] Red Deer Code Generator Component Tests ............ SUCCESS [  0.009 s]
[INFO] Red Deer UI Tests .................................. SUCCESS [  0.008 s]
[INFO] Red Deer Features .................................. SUCCESS [  0.001 s]
[INFO] Red Deer Eclipse Feature ........................... SUCCESS [  0.005 s]
[INFO] Red Deer Examples Feature .......................... SUCCESS [  0.005 s]
[INFO] Red Deer GEF Spy Feature ........................... SUCCESS [  0.005 s]
[INFO] Red Deer RCP Feature ............................... SUCCESS [  0.004 s]
[INFO] Red Deer SWT Feature ............................... SUCCESS [  0.004 s]
[INFO] Red Deer Tests Feature ............................. SUCCESS [  0.004 s]
[INFO] Red Deer UI Feature ................................ SUCCESS [  0.007 s]
[INFO] Red Deer Recorder Feature .......................... SUCCESS [  0.004 s]
[INFO] Red Deer JUnit Extensions Feature .................. SUCCESS [  0.003 s]
[INFO] Red Deer GEF/Graphiti Feature ...................... SUCCESS [  0.003 s]
[INFO] Red Deer Spy Feature ............................... SUCCESS [  0.004 s]
[INFO] Red Deer Log Parser Feature ........................ SUCCESS [  0.003 s]
[INFO] Red Deer Selenium Feature .......................... SUCCESS [  0.003 s]
[INFO] Red Deer Site ...................................... SUCCESS [  0.031 s]
[INFO] Red Deer Archetype ................................. SUCCESS [  0.056 s]
[INFO] Red Deer Snippets .................................. SUCCESS [  0.012 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:04 min
[INFO] Finished at: 2016-11-02T15:29:21+01:00
[INFO] Final Memory: 188M/648M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-versions-plugin:0.26.0:set-version (default-cli) on project parent: Execution default-cli of goal org.eclipse.tycho:tycho-versions-plugin:0.26.0:set-version failed: A required class was missing while executing org.eclipse.tycho:tycho-versions-plugin:0.26.0:set-version: org/eclipse/tycho/model/IU
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.tycho:tycho-versions-plugin:0.26.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/rasp/.m2/repository/org/eclipse/tycho/tycho-versions-plugin/0.26.0/tycho-versions-plugin-0.26.0.jar
[ERROR] urls[1] = file:/Users/rasp/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[2] = file:/Users/rasp/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[3] = file:/Users/rasp/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[4] = file:/Users/rasp/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[5] = file:/Users/rasp/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/Users/rasp/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[7] = file:/Users/rasp/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
[ERROR] urls[8] = file:/Users/rasp/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.7/plexus-utils-3.0.7.jar
[ERROR] urls[9] = file:/Users/rasp/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
[ERROR] urls[10] = file:/Users/rasp/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
[ERROR] urls[11] = file:/Users/rasp/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
[ERROR] urls[12] = file:/Users/rasp/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[13] = file:/Users/rasp/.m2/repository/org/eclipse/tycho/org.eclipse.osgi.compatibility.state/1.0.200.v20160504-1419/org.eclipse.osgi.compatibility.state-1.0.200.v20160504-1419.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.jboss.reddeer:parent:1.2.0.Final, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.eclipse.tycho.model.IU
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException`

**Pull request merged**
