### PR TITLE
Mockito dependency not found during installation

### PR DESCRIPTION
**Pull request by mmalina**
Cannot complete the install because one or more required items could not be found.
  Software being installed: RedDeer Tests Feature 0.8.0.201507130720 (org.jboss.reddeer.tests.feature.feature.group 0.8.0.201507130720)
  Missing requirement: RedDeer JUnit Component Tests 0.8.0.201507130720 (org.jboss.reddeer.junit.test 0.8.0.201507130720) requires 'bundle org.mockito 1.9.5' but it could not be found
  Cannot satisfy dependency:
    From: RedDeer Tests Feature 0.8.0.201507130720 (org.jboss.reddeer.tests.feature.feature.group 0.8.0.201507130720)
    To: org.jboss.reddeer.junit.test [0.8.0.201507130720]

### CODE REVIEW

**Comment by mmalina** [comment]
Awesome, thanks @nickboldt , it works for me. PR attached. @jpeterka please apply.

**Comment by vpakan** [comment]
Verification jobs failed please add prefix 'rev_' only in case when verification job has finished with success.

**Comment by mmalina** [comment]
test this

**Comment by mmalina** [comment]
It turns out our shared settings.xml didn't have jboss pluginRepository set up, only the regular repository. I fixed it. Let's see now.

**Comment by mmalina** [comment]
@jpeterka with the latest update site at http://download.jboss.org/jbosstools/mars/snapshots/builds/reddeer_master/ (>= B660) this is fixed - the Eclipse Orbit update site is added automatically, so the dependency is resolved fine.

**Comment by nickboldt** [comment]
Just checked your latest build and I see you're linking to http://download.eclipse.org/tools/orbit/downloads/drops/S20150519210750/repository ... I believe there's a policy in place to never link to eclipse.org sites due to performance concerns and unexpected mirror behaviour. Maybe you want to use one of these sites instead?
* http://download.jboss.org/jbosstools/mars/development/updates/
* http://download.jboss.org/jbosstools/updates/requirements/orbit/R20150519210750/

@maxandersen WDYT?

**Comment by mmalina** [comment]
@jpeterka what say you? :)

**Pull request closed without merging**
