### PR TITLE
apodhrad_Mars_TabbedPropertiesTest

### PR DESCRIPTION
**Pull request by ljelinkova**

### CODE REVIEW

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Mac job failed again but it seems to be a norm now so I am marking this issue for review anyway

**Comment by apodhrad** [comment]
The following issues were fixed
1. Opening an editor may take a while - added a wait condition
2. Shell title is changed when the editor is opened - fixed in setFocus() method

Lets think about what can be wrong with the change in method setFocus().

**Comment by apodhrad** [comment]
I don't see any issue with the change number 2; pushed to master

**Pull request closed without merging**
