### PR TITLE
ljelinko_Create java requirement

### PR DESCRIPTION
**Pull request by rhopp**

### CODE REVIEW

**Comment by rhopp** [comment]
`@JRE` matches any configuration. 
`@JRE(<double>)` matches just exact version of java defined in configuration (for example `@JRE(1.7)` matches configuration with  `<jre:version>1.7</jre:version>`

If there is need to do matching like >=, >, <, ... let me know.

**Comment by ljelinkova** [comment]
- add comment to JREsPreferencePage class
- you may use new FinishButton() instead of new PushButton("Finish")
- getJREs should not return TreeItem but you should create your own type (like in RuntimePreferencePage there is Runtime)
- I would move validateJRELocation directly to the JRERequirement since this is quite specific operation 
- @JRE - add cleanup method

**Comment by rhopp** [comment]
I didn't do bullet "I would move validateJRELocation directly to the JRERequirement since this is quite specific operation" because validateJRELocation is using internal stuff (from package which is not exported). Otherwise it should be ok.

**Comment by rhopp** [comment]
test this

**Comment by ljelinkova** [comment]
All is OK except that JREsPreferencePage still does not have a class comment.

**Pull request merged**
