### PR TITLE
Allow to create screenshots even in code

### PR DESCRIPTION
**Pull request by mlabuda**
to use like ScreenshotCapturer.capture(fileName) or similar.

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by jpeterka** [comment]
Please rebase and resolve conflicts and provide documentation or create doc issue.

**Comment by mlabuda** [comment]
#1143  doc issue

**Comment by jpeterka** [comment]
Some more findings:
1) when captureScreenshot is called without extension  java.lang.StringIndexOutOfBoundsException is thrown and it's not handled properly. Argument should be checked and error should be handled better
2) javadoc for captureScreenshot refers "File name has to contain file extension (e.g. .png)" but actually when other extension is used (like .tiff) it's png file anyway. 
3)default file path should for custom screenshots should be target/screenshots or target at least.

**Pull request closed without merging**
