### PR TITLE
CleanWorkspace requirement should close all editors before deleting projects

### PR DESCRIPTION
**Pull request by rawagner**
And also delete via deleteAllProjects() - might be faster

### CODE REVIEW

**Comment by rawagner** [comment]
depends on #1041

**Comment by rawagner** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
The verification job has failed due to timeout on mac, lets' try it again

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
verification job has passed (except LabeledTextTest.setFocusTest)

pushed to master

**Pull request closed without merging**
