### PR TITLE
jpeterka_JBIDE-18772: deploy with "mvn clean verify -Pdeploy-to-jboss.org"

### PR DESCRIPTION
**Pull request by mmalina**
Add profile for deploying RedDeer update site to jboss.org.
More details at https://issues.jboss.org/browse/JBIDE-18772
This is basically a copy of this profile from
https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml

### CODE REVIEW

**Comment by mmalina** [comment]
@mickaelistria do you think this will work? Can you review, please?
Currently the update site is here: http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/

I'm curious about these variables:
${JOB_NAME}/${BUILD_ID}-B${BUILD_NUMBER} 
I guess they will need to be added to the maven call in the job, right?

**Comment by mickaelistria** [comment]
The patch looks good.
about the variables, Jenkins passes them to Maven without requiring specific effort. See for example the configuraion of a CI job such as jbosstools-livereload to see how "mvn deploy -Pdeploy-to-jboss.org" is invoked.
However, it's not mandatory to use the JOB_NAME and BUILD_ID. For example, you could prefer using ${project.name} instead of ${JOB_NAME} and to skip ${BUILD_ID}. But this would publish to new URLs.

**Comment by mmalina** [comment]
@mickaelistria : Thanks! I think for now we will be happy with exactly the same output directory as we have now.
One more question: The mechanism that makes RedDeer_master/ point to e.g. http://download.jboss.org/jbosstools/mars/snapshots/builds/RedDeer_master/2015-06-05_08-21-04-B623/all/repo/ (via the compositeArtifacts.xml and compositeContent.xml) is separate from the deploy profile? Or how does that work? Because the rsync.sh only publishes to the subdirectory, no?

**Comment by mickaelistria** [comment]
the rsync.sh also takes care of updating the composite in RedDeer_master/ .

**Comment by mmalina** [comment]
The linux build passed and since this does not affect any testing (it's just a snipped in the site/pom.xml to publish the update site) that should be fine I guess.

**Pull request merged**
