### PR TITLE
rawagner_ToolBarMenu represents menu of view. It should be renamed

### PR DESCRIPTION
**Pull request by rhopp**
Followup of #748

### CODE REVIEW

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
Failed only on org.jboss.reddeer.swt.test.impl.text.LabeledTextTest.setFocusTest. Ready for review.

**Comment by rawagner** [comment]
MenuLookup.getToolbarMenus() Is part of API so it should not be renamed just like that. Please deprecate that method and create new one for getViewMenus.
Im also adding label API - and creating issue to check documentation to reflect these changes

**Comment by rhopp** [comment]
Thanks for noticing! I'm on it.

**Comment by rhopp** [comment]
PR updated. Please review also #1058 (doc issue, waiting for review).

**Comment by rawagner** [comment]
please rebase on master. Otherwise PR looks good

**Pull request closed without merging**
