### PR TITLE
use neon as TP and as publishingPath

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by nickboldt** [comment]
If this is rejected and you stick with a /mars/ path for publishing, then you'll need to fix your .p2f file in integration-tests here:

https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/InstallDependencies.p2f#L238

instead of using 

http://download.jboss.org/jbosstools/neon/snapshots/builds/reddeer_master/

**Comment by vpakan** [comment]
test this

**Comment by jpeterka** [comment]
We stay on Mars until 1.0 release.
@mmalina check what/if changes are needed

**Comment by jpeterka** [comment]
resolved

**Comment by rawagner** [comment]
Reopening. @mmalina  please check what/if changes are needed, then we will close this issue

**Comment by rawagner** [comment]
I missed the last comment. Closing

**Pull request closed without merging**
