### PR TITLE
Document parameterized tests

### PR DESCRIPTION
**Pull request by rhopp**
Related issue: #523

### CODE REVIEW

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
Verification job shows not compilation error. Please, leave this issue open after merging, so the documentation can be reviewed again (if it is possible. I don't know what is the workflow for this).

**Comment by vpakan** [comment]
Please create new issue to verify snippets after this issue is merged and new version of snippets is available

**Comment by vpakan** [comment]
Changes pushed to master please create issue to verify snippets once new version is published

**Comment by rhopp** [comment]
Followup issue: #1150

**Pull request closed without merging**
