### PR TITLE
Add New Maven Project wizard 

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by ljelinkova** [comment]
Please correct the comment in MavenProjectWizardArchetypePage and add test for this new functionality.

**Comment by rawagner** [comment]
I had a test somewhere, but it got lost!

**Comment by ljelinkova** [comment]
Maybe a dog ate it!

**Comment by rawagner** [comment]
Test added

**Comment by ljelinkova** [comment]
test is failing

**Comment by rawagner** [comment]
test this

**Pull request closed without merging**
