### PR TITLE
jpeterka_org.jboss.reddeer.swt.test.EditorBarTest.workbenchToolBarTest is failing

### PR DESCRIPTION
**Pull request by rhopp**
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix/jdk=sunjdk1.7,label=firebird/668/testReport/junit/org.jboss.reddeer.swt.test/EditorBarTest/workbenchToolBarTest_default/?

Error Message

Timeout after: 10 s.: shell with text matching"New" is active
Stacktrace

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: shell with text matching"New" is active
	at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:159)
	at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:112)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
	at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:41)
	at org.jboss.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:25)
	at org.jboss.reddeer.swt.test.EditorBarTest.prepare(EditorBarTest.java:37)

### CODE REVIEW

**Comment by jpeterka** [comment]
Wouldn't be safer to change it to ?
```java
new WaitUntil(new ShellWithTextIsAvailable("New"));
new DefaultShell("New");
```

**Comment by rawagner** [comment]
@jpeterka  its basically the same. DefaultShell will wait for 5sec for "New" shell to appear.

**Comment by rhopp** [comment]
Nope... That wait was the thing which was causing the trouble. After the "New" shell was opened, on Firebird no shell had focus, thus the wait failed. `new DefaultShell("New");` waits for the shell to appear even though it appears unfocused and activates it afterwards.

**Comment by rhopp** [comment]
So I guess we can say, that using `WaitUntil(ShellWithTextIsActive)` for waiting for shell to open could be considered bad practice as it can fail on some platforms and instead of that we should use `new DefaultShell("text")`.
Note, that using `ShellWithTextIsActive` condition with WaitWhile for waiting for shell to close is OK.

**Comment by jpeterka** [comment]
Ok, let's keep it like this. There is timeout 10s by default for this which is more than enough for this case. ShellWithTextAVAILABLE condition would be too much, you're right.

**Comment by jpeterka** [comment]
Please add fixes #no next time into commit message

**Pull request closed without merging**
