### PR TITLE
ljelinko_Remove logDebug property

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
ready for review

**Comment by ljelinkova** [comment]
RedDeerPropertiesTest uses logDebug property as an example property for testing if the RedDeerProperties function properly. Please do not remove tests but change them to use another property.

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Comment applied. Ready for review.

**Comment by vpakan** [comment]
Please create issue to update documentation according to changes and link it here

**Comment by jpeterka** [comment]
Issue created #1069

**Comment by ljelinkova** [comment]
Jenkins job failed on Windows. Please mark issue for review only after you're sure all tests passed / could be ignored.

**Comment by jpeterka** [comment]
I did check the verification job and was ok, see http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1043/artifact/reddeermatrixtestresults.html . Not sure where you were looking.

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Ready for review - job looks good http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1064/artifact/reddeermatrixtestresults.html

**Pull request closed without merging**
