### PR TITLE
rev_Create condition WidgetIsAvailable/WidgetIsFound

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Job looks ok, ready for review:
http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1333/artifact/reddeermatrixtestresults.html

**Comment by vpakan** [comment]
Please add javadoc to public methods in WidgetLookup.java

**Comment by jpeterka** [comment]
Javadoc added.

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Ready for review, job doesn't look that good, OSX failed but it's not related because I've just added javadoc since the last verification job that passed.

**Pull request closed without merging**
