### PR TITLE
rawagner_SWT plugin refactoring

### PR DESCRIPTION
**Pull request by mlabuda**

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this.

**Comment by mlabuda** [comment]
test this.

**Comment by mlabuda** [comment]
test this

**Comment by rawagner** [comment]
- WorkbenchShell should be moved to Workbench plugin
- fix import of WaitCondition in all swt plugin's conditions

**Pull request merged**
