### PR TITLE
Log level support for RedDeer logging

### PR DESCRIPTION
**Pull request by jpeterka**
There was request to add log level support filtering for RedDeer similar to as it work in log4j

### CODE REVIEW

**Comment by ljelinkova** [comment]
retest this

**Comment by ljelinkova** [comment]
You should add some basic tests for the logger. For example. when I type log.fatal("xyz"); or log.dump("xyz")  it now fails with 

```
org.jboss.reddeer.common.exception.RedDeerException: Unsupported log level
	at org.jboss.reddeer.common.logging.Logger.getLevelFromMsgType(Logger.java:293)
	at org.jboss.reddeer.common.logging.Logger.print(Logger.java:261)
	at org.jboss.reddeer.common.logging.Logger.dump(Logger.java:186)
	at a.a.test(a.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.jboss.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:56)
	at org.jboss.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:115)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ljelinkova** [comment]
Please order LogLevel enum according the priority - starting from "ALL" to "OFF"

**Comment by jpeterka** [comment]
Missing types mapping fixed

**Comment by jpeterka** [comment]
LogLevel is sorted same way as it's used in log4j for example, see https://logging.apache.org/log4j/2.x/manual/customloglevels.html , I would not rather reverse in opposite way. Let's stay compatible with common logging systems when possible.

**Comment by jpeterka** [comment]
retest this please

**Comment by ljelinkova** [comment]
I am sorry, I misunderstood meaning of OFF and ALL at first. You're right, it is sorted correctly.

**Comment by ljelinkova** [comment]
I still think you should add simple test that would at least call all log methods to ensure that thery work and do not fail.

**Comment by jpeterka** [comment]
Simple test added

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by jpeterka** [comment]
retest this

**Comment by jpeterka** [comment]
retest this

**Comment by jpeterka** [comment]
retest this

**Comment by jpeterka** [comment]
retest this

**Pull request closed without merging**
