### PR TITLE
vpakan_Create snippets for documentation

### PR DESCRIPTION
**Pull request by mlabuda**

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
Failing tests are not caused by this PR.

**Comment by vpakan** [comment]
https://github.com/jboss-reddeer/reddeer/pull/1077/files#diff-9170ef0c0e5b50ec36375a5d0b7062d8R17 - WORKSPACE_DIRECTORY property should not be initialized to ${WORKSPACE} because it will work only for jobs running on jenkins. Default value should be  '." I guess so it will work also when run manually via maven on local machine.

And also in Javadoc varialble ${WORKSPACE} should be replaced with WORKSPACE_DIRECTORY

**Pull request merged**
