### PR TITLE
Remove ConstructorFinishedSuccessfully

### PR DESCRIPTION
**Pull request by rawagner**
https://github.com/jboss-reddeer/reddeer/blob/master/plugins/org.jboss.reddeer.core/src/org/jboss/reddeer/core/condition/ConstructorFinishedSuccessfully.java

### CODE REVIEW

**Comment by odockal** [comment]
@rawagner Could you please take a look at compilation error?

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@odockal fixed, build hovewer failed (at last step) because eclipse repositories went down. Lets not waste time by running tests again and push it anyway. Thanks!

**Comment by odockal** [comment]
@rawagner Definitely! Merged...

**Pull request merged**
