### PR TITLE
jpeterka_Implement Edit button on RuntimePreferencePage

### PR DESCRIPTION
**Pull request by ljelinkova**

### CODE REVIEW

**Comment by ljelinkova** [comment]
test this

**Comment by ljelinkova** [comment]
test this

**Comment by ljelinkova** [comment]
test this

**Comment by jpeterka** [comment]
* "Opens tie runtime's edit dialog" Should be "Opens the" or "Opens a" I guess
* @param name - missing param description

**Comment by jpeterka** [comment]
Pushed to master. Next time please add fixes #issue_number into commit message.

**Pull request closed without merging**
