### PR TITLE
Logging messages quotes in o.j.r.eclipse and o.j.r.workbench

### PR DESCRIPTION
**Pull request by jpeterka**
sub-issue of #764

### CODE REVIEW

**Comment by jpeterka** [comment]
ready for review, verification job looks ok, errors are not related to PR - http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1084/artifact/reddeermatrixtestresults.html

**Comment by vpakan** [comment]
Verification job failed on Mac only 112 tests have been run please rerun.

**Comment by jpeterka** [comment]
Thanks for pointing this, I don't know where I was looking.

**Comment by jpeterka** [comment]
Retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by vpakan** [comment]
test this

**Comment by jpeterka** [comment]
finally passed on osx - https://github.com/jboss-reddeer/reddeer/pull/1082 , ready for review

**Pull request closed without merging**
