### PR TITLE
Add Secure Storage Requirement

### PR DESCRIPTION
**Pull request by odockal**
Add new secure storage requirement that switches off master password providers.

### CODE REVIEW

**Comment by rawagner** [comment]
@odockal please consider switching off the property using direct API (see org.jboss.reddeer.direct)

**Comment by odockal** [comment]
Going to take a look at it now. Thanks!

**Comment by odockal** [comment]
I did not succeed to find correct plugin id and its key that could switch password providers in Security Storage. I think that concrete providers are generated dynamically.

**Comment by odockal** [comment]
Closing this PR due to insufficient implementation of this area. Will be solved/extended later.

**Pull request closed without merging**
