### PR TITLE
Create wizard for creating Red Deer test

### PR DESCRIPTION
**Pull request by ljelinkova**

### CODE REVIEW

**Comment by ljelinkova** [comment]
Test this

**Comment by ljelinkova** [comment]
Test this

**Comment by ljelinkova** [comment]
Test this

**Comment by ljelinkova** [comment]
Test this

**Comment by vpakan** [comment]
test this

**Comment by vpakan** [comment]
* add test for this new wizard
* create documentation issue to document this new wizard

**Comment by ljelinkova** [comment]
Created documentation issue #1263. 
There are no tests for Eclipse UI component but there has already been created an issue #1204

**Pull request closed without merging**
