### PR TITLE
jpeterka_Reorganize RedDeer features

### PR DESCRIPTION
**Pull request by rawagner**
RedDeer features are bit messy
* swt.go is part of Eclipse feature should be RCP or could be separate feature
* rcp feature contains to many plugins (Selenium, Gef...)

### CODE REVIEW

**Comment by rawagner** [comment]
I didn't add go as a part of eclipse feature because go requires junit.extensions and requirements which are not part of RCP feature

**Comment by vpakan** [comment]
* remove selenium plugin from Eclipse feature
* rename "GO" plugin to "Go"

**Comment by rawagner** [comment]
fixed..hopefully..

**Comment by jpeterka** [comment]
How about selenium feature? Do we want to have it in 1.0 list although it has no API at all (it's entirely empty plugin so far) ?

**Comment by vpakan** [comment]
Selenium is added as separate feature for future use and is not included in any category so it's not visible in install dialog unless user wants to see uncategorized content

**Comment by jpeterka** [comment]
If it's not visible then it's ok for me.

**Pull request closed without merging**
