### PR TITLE
Improved Keyboard stability

### PR DESCRIPTION
**Pull request by jpeterka**
There are several tests that are failing because of Keyboard impl. issues. Let's make some attempts howto make it more stable.

### CODE REVIEW

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by vpakan** [comment]
Last verification job failed and results of previous verification jobs are not available anymore. Please run it again.

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Job looks ok: http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1418/artifact/reddeermatrixtestresults.html

**Pull request closed without merging**
