### PR TITLE
Update RedDeer version to 2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by mmalina**
Command used for upversioning:
mvn org.eclipse.tycho:tycho-versions-plugin:0.22.0:set-version -DnewVersion=2.0.0-SNAPSHOT

In addition, these files were modified manually:
archetype/pom.xml
archetype/src/main/resources/META-INF/maven/archetype-metadata.xml

This command was used to update the bundle ranges:
find . -iname MANIFEST.MF -ipath '*/META-INF/M*'|xargs perl -pi -e 's/\[1.3(.0)?,1.4(.0)?\)/[2.0,2.1)/'

### CODE REVIEW

**Comment by rawagner** [comment]
can you please fix the conflict ?

**Comment by mmalina** [comment]
@rawagner you should have merged this first and then it would be Ondra's problem :) (b29bd98)

**Comment by mmalina** [comment]
@rawagner rebased and resolved the conflict.

**Comment by rawagner** [comment]
pushed to master, thanks!

**Pull request merged**
