### PR TITLE
Switch RedDeer to Eclipse Mars

### PR DESCRIPTION
**Pull request by jpeterka**
Update RedDeer to use Eclipse Mars instead of Luna

### CODE REVIEW

**Comment by vpakan** [comment]
50+ tests has failed I suggest to not apply this PR until those tests are fixed

**Comment by jpeterka** [comment]
I agree, these related issues were created:
https://github.com/jboss-reddeer/reddeer/issues/1023
https://github.com/jboss-reddeer/reddeer/issues/1024
https://github.com/jboss-reddeer/reddeer/issues/1025

**Comment by apodhrad** [comment]
Why is the milestone set to 0.8.0? I think we decided that 0.8.0 will luna-based release, didn't we?

**Comment by vpakan** [comment]
Could you rebase your branch and pusu it to your repo please?

**Comment by jpeterka** [comment]
@apodhrad 0.8 was meant to be Mars release since the beginning AFAIK

**Pull request merged**
