### PR TITLE
rev_Add a logic for testing whether an issue was fixed

### PR DESCRIPTION
**Pull request by apodhrad**
Usually tests fail due to a known issue, so if the issue is reported we don't have run the test. Moreover, we should also add an option for disabling such behaviour.

Example:
```java
@JIRA("SWITCHYARD-2782", "CLOSED")
public void rulesChannelTest() {
  ...
}
```

The test above would be executed only if the issue is closed. My idea is not to provide particular implementions (JIRA, Bugzilla, ...) but only an abstract logic.

Maybe we can use the existing implementation RunIf.

### CODE REVIEW

**Comment by vpakan** [comment]
Any update?

**Comment by vpakan** [comment]
Add copyright and licence information to newly created classes

**Comment by apodhrad** [comment]
This PR is ready to be merged

**Comment by apodhrad** [comment]
Is tehre any template for the copyright license?

**Comment by vpakan** [comment]
See this commit https://github.com/jboss-reddeer/reddeer/commit/49bcb235cb81844cb28e6a19afb3a4184907d8e6

**Comment by apodhrad** [comment]
test this

**Comment by rawagner** [comment]
any progress ?

**Comment by rawagner** [comment]
for 1.0.x too

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Pull request closed without merging**
