### PR TITLE
Requirements should cleanup after themselves

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
Be aware that this will break jbosstools-integration-tests reddeer plugins because I added a method to Requirement interface

**Comment by ljelinkova** [comment]
- please add comments to public classes and methods
- I think that requirements should be cleaned up after afterClass methods
```
    @Override
    public void evaluate() throws Throwable {
        requirements.cleanUp();
        statement.evaluate();
    }
```
- there is test suite `RequirementsTestSequenceSuite` testing the proper order of requirements fullfilling, @Before, @BeforeClass etc. methods, it should be extended also for cleanup method
- in `ServerRequirement.cleanup()` I do not think you should have `lastServerConfiguration != null` in the condition
- you should extend tests for `ServerRequirement` to test the cleanup behavior

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
I've fixed/added all things as you suggested but i kept  `lastServerConfiguration != null`

**Comment by rawagner** [comment]
test this

**Comment by ljelinkova** [comment]
test this

**Comment by ljelinkova** [comment]
Pushed to master

**Comment by ljelinkova** [comment]
@rawagner  Please create Jira for doc update

**Comment by rawagner** [comment]
created #1056

**Pull request closed without merging**
