### PR TITLE
Clean up deprecated code and its usage

### PR DESCRIPTION
**Pull request by mlabuda**

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by ljelinkova** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by vpakan** [comment]
Please do not mark PR with +170 failed tests for review. I will rerun verification job check results and act appropriately to verification job results

**Comment by vpakan** [comment]
test this

**Pull request closed without merging**
