### PR TITLE
Create tests for Reddeer wizards #1065

### PR DESCRIPTION
**Pull request by jrichter1**

### CODE REVIEW

**Comment by jpeterka** [comment]
Please add test proving that example test is without errors.

**Comment by jrichter1** [comment]
test this

**Comment by jrichter1** [comment]
test this

**Comment by vpakan** [comment]
* add this new test plugin to org.jboss.reddeer.tests.feature/feature.xml
* add copyright and licence information to newly created classes

**Comment by jrichter1** [comment]
Done and done.

**Pull request closed without merging**
