### PR TITLE
SQL Result View implemented

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by ljelinkova** [comment]
@jpeterka  This PR has been here for almost half a year. Please finish it or drop it.

**Comment by jpeterka** [comment]
Retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
@ljelinkova: this one is blocked by #760, moving to 0.8

**Comment by vpakan** [comment]
#760 is fixed now so just rebase on tip of master and make appropriate changes reflecting RedDeer refactoring

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
ready for review, verification job look ok - http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1083/artifact/reddeermatrixtestresults.html

**Pull request closed without merging**
