### PR TITLE
Views - make sure that widgets are looked up within correct ctabitem

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by odockal** [comment]
@rawagner Could you take a look at the conflicts?

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@odockal tests are ok. please review

**Pull request merged**
