### PR TITLE
Unify naming convention for exec parameters

### PR DESCRIPTION
**Pull request by apodhrad**
See https://github.com/jboss-reddeer/reddeer/wiki/RedDeer-execution-parameters

### CODE REVIEW

**Comment by apodhrad** [comment]
This PR also requires update the parameters in all jenkins jobs

**Comment by vpakan** [comment]
create issue for updating documentation

**Comment by apodhrad** [comment]
* created at #1305 
* was updated too, see RedDeerLauncherProperties.java
* yes

**Comment by ljelinkova** [comment]
All seems OK except for RedDeerLauncherProperties.getByName. This method was created when we introduced rule that all RD properties have to start with "reddeer" prefix to help to migrate existing launchers. So the method checked if the RD property contains "reddeer" prefix or not. 

The new implementation should be something like this:

{code}
private static RedDeerProperties getByName(String name){
		if (name.startsWith(REDDEER_PARAMETER_PREFIX)){
			return RedDeerProperties.getByName(name);
		} else {
			return RedDeerProperties.getByName(name.replace("reddeer.", "rd."));
		}
	}
{code}

**Comment by jpeterka** [comment]
Seems that all comments were resolved here, let's apply and see then. Pushed to master.

**Pull request closed without merging**
