### PR TITLE
ResultView.removeAllResults() should wait until results view is empty

### PR DESCRIPTION
**Pull request by jpeterka**
See this verification job /job/RedDeer_master_matrix/jdk=sunjdk1.7,label=orion64

### CODE REVIEW

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Don't be surprised, there is still testSQLResultViewFail failing sometimes but it's unrelated to this PR.

**Comment by vpakan** [comment]
Too many failed tests and MS Windows tests didn't run at all I will rerun tests please check the results and act accordingly.

**Comment by vpakan** [comment]
test this

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Verification job looks ok, PR ready for review - http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix_report/1217/artifact/reddeermatrixtestresults.html

**Pull request closed without merging**
