### PR TITLE
Add test for selecting project item

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
retest this

**Comment by ljelinkova** [comment]
@rawagner Any update on this?

**Comment by rawagner** [comment]
This PR is targeting RD 1.1.0

**Comment by ljelinkova** [comment]
Sorry, my bad

**Comment by rawagner** [comment]
retest this

**Comment by rawagner** [comment]
retest this

**Comment by rawagner** [comment]
I've experienced issues with selecting project but very rarely. That's why Im adding this test to reddeer.

**Pull request closed without merging**
