### PR TITLE
PropertiesView doesn't wait for tabs to be rendered

### PR DESCRIPTION
**Pull request by jomarko**
If user changes properties of many elements, ProeprtiesView doesn't care about fact, that tabs can be rendered with delay.

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by apodhrad** [comment]
please add a test for the method selectTab()

**Comment by jomarko** [comment]
@apodhrad , do you think that this test [1] is not convenient?

[1]
https://github.com/jomarko/reddeer/blob/master/tests/org.jboss.reddeer.eclipse.test/src/org/jboss/reddeer/eclipse/test/ui/views/properties/TabbedPropertiesTest.java#L71

**Comment by apodhrad** [comment]
@jomarko you are absolutely right, I didn't notice that test.

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
