### PR TITLE
Fix: ViewMenu cannot manipulate with check styled menus

### PR DESCRIPTION
**Pull request by tsedmik**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by tsedmik** [comment]
related to #1359

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
@rawagner  do you have any idea why the verification job is not executed?

**Comment by rawagner** [comment]
Only master branch was whitelisted. I've changed it to * - it might help

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Pull request merged**
