### PR TITLE
RedDeer Spy view implemented

### PR DESCRIPTION
**Pull request by mlabuda**
aka Eclipse SWT Spy

### CODE REVIEW

**Comment by mlabuda** [comment]
GEF Spy has been moved to separated plugin and spy plugin is used for general RedDeer Spy.

**Comment by mlabuda** [comment]
Test this.

**Comment by mlabuda** [comment]
test this

**Comment by vpakan** [comment]
* plugins/org.jboss.reddeer.gef.spy/pom.xml - name should by Red Deer GEF Spy Component
* features/org.jboss.reddeer.gef.spy.feature/feature.xml - copyright should contain year 2015
* add both spy features to RedDeer Tools category

**Comment by vpakan** [comment]
Sorry I missed these minor issues please fix it:
* plugins/org.jboss.reddeer.gef.spy/META-INF/MANIFEST.MF - Bundle-Name should be "RedDeer GEF Spy"
* features/org.jboss.reddeer.gef.spy.feature/feature.properties - copyright date should contain 2015 year
* plugins/org.jboss.reddeer.gef.spy/plugin.xml - name of the view should be "RedDeer GEF Spy" or "RedDeer GEF Spy view"
* plugins/org.jboss.reddeer.spy/plugin.xml - name of the view should be "RedDeer Spy " or ""RedDeer Spy view" but similar as above

**Comment by vpakan** [comment]
features/org.jboss.reddeer.gef.spy.feature/feature.xml - remove org.jboss.reddeer.recorder plugin

**Pull request closed without merging**
