### PR TITLE
Add activation of view to Project methods

### PR DESCRIPTION
**Pull request by ljelinkova**

### CODE REVIEW

**Comment by ljelinkova** [comment]
retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
test this

**Comment by vpakan** [comment]
* I don't agree to add AbstractExplorer as additional parameter to constructors. TreeItem is unique information for each object encapsulating it. Lets discuss it on our meeting I have more comments
* javadoc should be updated for new constructors
* instead of activating item it's actually selected is this correct expected behavior?
* we assert input parameter TreeItem is not null but we allow input parameter AbstractExplorer to be null so either we should restrict AbstractExplorer to not be null or do not mark old constructors without AbstractExplorer ot be deprecated they should just call new constructors with null provided as AbstractExplorer input parameter

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Comment by ljelinkova** [comment]
Retest this

**Pull request closed without merging**
