### PR TITLE
dev_Some refactoring and multiple references to deprecated usage fixed

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by vpakan** [comment]
test this

**Comment by vpakan** [comment]
Please next time use more descriptive commit message

**Comment by jpeterka** [comment]
retest this please

**Comment by jpeterka** [comment]
Noticed this PR breaks API compatibility, I need to fix it.

**Comment by jpeterka** [comment]
Closing this one, will not be applied as it breaks API

**Pull request closed without merging**
