### PR TITLE
Wait for shell active in quickfix wizard

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by apodhrad** [comment]
looking

**Comment by apodhrad** [comment]
@rawagner why did you change the condition? I think that we have to wait until the shell disappears (and not only until it loses its focus).

**Comment by rawagner** [comment]
When you click on finish in quickfix dialog, often it will cause another dialog to appear and Quickfix dialog is still present and waiting for new dialog to finish.

**Comment by apodhrad** [comment]
test this

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
